name: Test Project
on:
  pull_request:
    branches: ['main', 'dev'] 
    types: [opened, synchronize, reopened]
  push:
    branches: ['main', 'dev'] 

jobs:
  build:
    name: Build Project and Test Code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
  
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2
  
      - name: Install dependencies
        run: bundle install

      - name: Run Rspec test suite
        run: rake spec

      - name: Run Cucumber Tests
        run: rake cucumber

      - name: Send test coverage to Coveralls.io
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
